Route7_MapScripts::
	.byte 
	
Route7_Man::
	msgbox Route7_Text_Man, MSGBOX_NPC
	end

Route7_Text_Man:
	.string "{COLOR}{BLUE}This is it.\n"
	.string "The foot of Mt. Tamarok.\p"
	.string "There's no better training for your\n"
	.string "Pokémon than this rough climb through\l"
	.string "the ice and snow.\p"
	.string "Many fail.\p"
	.string "The ones who succeed may have a chance\n"
	.string "at the tournaments at Northstar City.\p"
	.string "I hope you're ready for the ride…\n"
	.string "I know I am.$"
